### ISSUE TITLE
mingw32-float.h.patch problem

### ISSUE THREAD

**Issue by revelator** [jmeubank/tdm-gcc-src#1]
Welcome back m8 :) 

The mingw32-float.h.patch gets circumvented by changes to gcc's build chain which now uses a sed script to do allmost the same as your patch, so we end up with two #include_next<float.h>.

One from your patch and another unguarded one from the sed script.

`#if defined (__MINGW32__) && ! defined (_MINGW_FLOAT_H_)
/* MinGW.org's runtime libraries provide a supplementary float.h, which
 * must also be included to complement this one.  Ideally that MinGW.org
 * header should be included first, and it will include this one, but in
 * a default configuration it doesn't normally happen this way; when we
 * didn't see it first, include the MinGW.org header now!
 */
# include_next <float.h>
#endif

#endif /* _FLOAT_H___ */
#include_next <float.h>`

**Comment by jmeubank** [comment]
I'm missing some context here, what version of what file in what package is this happening in?

Nevermind, spotted it in `lib\gcc\x86_64-w64-mingw32\9.2.0\include\float.h`.

**Comment by revelator** [comment]
exactly ;) the guard gets circumvented by the unguarded include.
Not sure how to go about fixing it in the build chain or if its even nessesary anymore ?.

**Comment by jmeubank** [comment]
This looks to be fixed in the upcoming TDM-GCC 10.3.0 release.
