### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by Yanren1225** [jmeubank/tdm-gcc-src#2]
cd "c:\Users\nihao\dock_menu\code\SJJG\Structure\" ; if ($?) { gcc *.c -o structure.exe } ; if ($?) { .\structure.exe }
gcc.exe: error: *.c: Invalid argument
gcc.exe: fatal error: no input files
compilation terminated.

**Comment by jmeubank** [comment]
Duplicate of https://github.com/jmeubank/tdm-gcc/issues/12 .
