### ISSUE TITLE
tmd64-gcc-9.2.0 problem with lib <iostream>

### ISSUE THREAD

**Issue by GMGuimaraes** [jmeubank/tdm-gcc-src#4]
I came to report an error with the library <iostream>
The only one I can't use in version 9.2.0
Whenever I import the library, these errors appear when trying to compile.
I love the ease of use of this compiler and the highlights, I hope I helped to find the error.

In file included from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/system_error:39,
                 from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/bits/ios_base.h:46,
                 from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/ios:42,
                 from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/ostream:38,
                 from C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/iostream:39,
                 from C:\Users\gmore\OneDrive\�rea de Trabalho\Fatorial.cpp:1:
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:53:25: error: 'EBADMSG' was not declared in this scope; did you mean 'EBADF'?
   53 |       bad_message =     EBADMSG,
      |                         ^~~~~~~
      |                         EBADF
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:71:31: error: 'EIDRM' was not declared in this scope
   71 |       identifier_removed =    EIDRM,
      |                               ^~~~~
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:89:21: error: 'ENOLINK' was not declared in this scope; did you mean 'EMLINK'?
   89 |       no_link =     ENOLINK,
      |                     ^~~~~~~
      |                     EMLINK
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:93:33: error: 'ENODATA' was not declared in this scope
   93 |       no_message_available =    ENODATA,
      |                                 ^~~~~~~
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:103:32: error: 'ENOSR' was not declared in this scope; did you mean 'ENOSPC'?
  103 |       no_stream_resources =    ENOSR,
      |                                ^~~~~
      |                                ENOSPC
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:112:26: error: 'ENOSTR' was not declared in this scope; did you mean 'ENOTTY'?
  112 |       not_a_stream =     ENOSTR,
      |                          ^~~~~~
      |                          ENOTTY
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:139:34: error: 'ENOTRECOVERABLE' was not declared in this scope
  139 |       state_not_recoverable =    ENOTRECOVERABLE,
      |                                  ^~~~~~~~~~~~~~~
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:142:28: error: 'ETIME' was not declared in this scope
  142 |       stream_timeout =     ETIME,
      |                            ^~~~~
C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:145:28: error: 'ETXTBSY' was not declared in this scope
  145 |       text_file_busy =     ETXTBSY,
      |                            ^~~~~~~

**Comment by jmeubank** [comment]
Works fine here. Can you check if the errno.h file is up-to-date? It should include definitions for those constants. You may need to wipe out your install and reinstall.

```
joeub@DESKTOP-1LUONFR MINGW64 /crossdev/gccmaster
$ grep -R EBADMSG /c/TDM-GCC-64-9.2.0/x86_64-w64-mingw32/include
/c/TDM-GCC-64-9.2.0/x86_64-w64-mingw32/include/errno.h:#ifndef EBADMSG
/c/TDM-GCC-64-9.2.0/x86_64-w64-mingw32/include/errno.h:#define EBADMSG 104

joeub@DESKTOP-1LUONFR MINGW64 /crossdev/tests
$ cat >iostream-test.cc <<EOF
> #include <iostream>
>
> int main() {
>   return 0;
> }
> EOF

joeub@DESKTOP-1LUONFR MINGW64 /crossdev/tests
$ /c/TDM-GCC-64-9.2.0/bin/g++ -o iostream-test.exe iostream-test.cc

joeub@DESKTOP-1LUONFR MINGW64 /crossdev/tests
$ ./iostream-test.exe

joeub@DESKTOP-1LUONFR MINGW64 /crossdev/tests
$
```
