### ISSUE TITLE
eh_shmem wholly incompatible with aslr

### ISSUE THREAD

**Issue by revelator** [jmeubank/tdm-gcc-src#5]
To my dismay i discovered that the eh_shmem.patch cannot be applied if building gcc with aslr (segfaults in gnattools and even if skipping gnat it will segfault to no end on even the simplest hello world example).

I suspect that it relies on set base adresses and does not play well with the dynamic base address feature from aslr, unfortunatly i have no idea how to fix this.

removing the patch gets around the problem but then we cannot throw exceptions across dll boundaries so its quite a conondrum.

Any ideas ?

**Comment by jmeubank** [comment]
Throwing some references here for how to solve this:
https://github.com/firebase/nginx/blob/master/src/os/win32/ngx_shmem.c
https://docs.microsoft.com/en-us/windows/win32/dlls/using-shared-memory-in-a-dynamic-link-library

**Comment by revelator** [comment]
Hmm interresting, though i would have to see the entire codebase for the ngx one :) it might just do the trick.

**Comment by revelator** [comment]
one thing i cant seem to find any info on is if the atomic string function windows types need set base addresses at all or if the windows api handles this internally ?. The nginx code is pretty interresting though and works in some ways pretty close to what is currently done with the atomic string types. On the other hand it is also somewhat more complicated to use so im a little afraid to experiment with it.

**Comment by jmeubank** [comment]
Good news, the 10.3.0 TDM-GCC release will include a newly updated version of the __SHMEM machinery. I observed segfaults in gnattools with the old version but the new version seems to run cleanly. It does not take into account ASLR and should not need to, as sections of the image are mapped dynamically into the new mechanism at runtime.

**Comment by revelator** [comment]
cool :)

**Comment by revelator** [comment]
do you get multiple definition errors with this when compiling it with gcc-10.3.0 ?

**Comment by revelator** [comment]
Btw heres a small improvement for the memset and memcpy code in the patch.

```
/*==================================Don't depend on libgcc=============================*/

/* use asm routines to unlink it completely from the runtimes */
static void *memset0(void * d, int s, size_t c)
{
    void * temp = d;
    __asm__ volatile (
        "rep stosb"
        :"=D"(d),"=c"(c)
        :"0"(d),"a"(s),"1"(c)
        :"memory"
    );
    return temp;
}

/* use asm routines to unlink it completely from the runtimes */
static void *memcpy0(void *d, const void *s, size_t c)
{
    void * temp = d;
    __asm__ volatile (
        "rep movsb"
        :"=D"(d),"=S"(s),"=c"(c)
        :"0"(d),"1"(s),"2"(c)
        :"memory"
    );
    return temp;
}

/*====================================================================================*/
```
